wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.14
    start_time: 1736939799
    t:
      1:
      - 1
      - 50
      - 55
      3:
      - 13
      - 15
      - 16
      - 35
      4: 3.10.14
      5: 0.12.21
      8:
      - 5
clip_predicted_values:
  desc: null
  value: true
close_environment_at_exit:
  desc: null
  value: true
disable_progressbar:
  desc: null
  value: false
discount_factor:
  desc: null
  value: 0.99
entropy_loss_scale:
  desc: null
  value: 0.03
environment_info:
  desc: null
  value: episode
experiment:
  desc: null
  value:
    checkpoint_interval: 50000
    directory: /workspace/Options_In_Simulation/my_runs/PPOc_rooms_r9_k_prog_LOW
    experiment_name: PPOc_rooms_r9_k_prog_LOW
    store_separately: false
    wandb: true
    wandb_kwargs:
      dir: /workspace/Options_In_Simulation/my_runs
      entity: meesjansen-Delft Technical University
      name: PPOc_rooms_r9_k_prog_LOW
      project: PPO_rooms
      tags:
      - PPOc
      - Rooms
    write_interval: 500
grad_norm_clip:
  desc: null
  value: 1.0
headless:
  desc: null
  value: true
kl_threshold:
  desc: null
  value: 0
lambda:
  desc: null
  value: 0.95
learning_epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0005
learning_rate_scheduler:
  desc: null
  value: skrl.resources.schedulers.torch.kl_adaptive.KLAdaptiveLR
learning_rate_scheduler_kwargs:
  desc: null
  value:
    kl_threshold: 0.02
learning_starts:
  desc: null
  value: 0
mini_batches:
  desc: null
  value: 64
policy:
  desc: null
  value:
    '0': Linear(in_features=5, out_features=256, bias=True)
    '1': ReLU()
    '2': Linear(in_features=256, out_features=128, bias=True)
    '3': ReLU()
    '4': Linear(in_features=128, out_features=64, bias=True)
    '5': ReLU()
    '6': Linear(in_features=64, out_features=2, bias=True)
random_timesteps:
  desc: null
  value: 0
ratio_clip:
  desc: null
  value: 0.2
rewards_shaper:
  desc: null
  value: null
rollouts:
  desc: null
  value: 1280
state_preprocessor:
  desc: null
  value: skrl.resources.preprocessors.torch.running_standard_scaler.RunningStandardScaler
state_preprocessor_kwargs:
  desc: null
  value:
    device: cuda:0
    size: Box(-10.0, 10.0, (5,), float32)
time_limit_bootstrap:
  desc: null
  value: false
timesteps:
  desc: null
  value: 500000
value:
  desc: null
  value:
    '0': Linear(in_features=5, out_features=256, bias=True)
    '1': ReLU()
    '2': Linear(in_features=256, out_features=128, bias=True)
    '3': ReLU()
    '4': Linear(in_features=128, out_features=64, bias=True)
    '5': ReLU()
    '6': Linear(in_features=64, out_features=1, bias=True)
value_clip:
  desc: null
  value: 0.2
value_loss_scale:
  desc: null
  value: 0.5
value_preprocessor:
  desc: null
  value: skrl.resources.preprocessors.torch.running_standard_scaler.RunningStandardScaler
value_preprocessor_kwargs:
  desc: null
  value:
    device: cuda:0
    size: 1
