name: ci
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install package + test deps
        run: python -m pip install -e ".[artifacts,dev]"
      - name: Run tests
        run: pytest -q
